# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ir_pb2
import ir_pb2_grpc

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ir_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModules = channel.unary_unary(
                '/ir.IRService/GetModules',
                request_serializer=ir_pb2.SourceRequest.SerializeToString,
                response_deserializer=ir_pb2.ModuleResponse.FromString,
                _registered_method=True)
        self.GetClasses = channel.unary_unary(
                '/ir.IRService/GetClasses',
                request_serializer=ir_pb2.SourceRequest.SerializeToString,
                response_deserializer=ir_pb2.ClassResponse.FromString,
                _registered_method=True)
        self.GetCFG = channel.unary_unary(
                '/ir.IRService/GetCFG',
                request_serializer=ir_pb2.SourceRequest.SerializeToString,
                response_deserializer=ir_pb2.CFGResponse.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_unary(
                '/ir.IRService/GetAll',
                request_serializer=ir_pb2.SourceRequest.SerializeToString,
                response_deserializer=ir_pb2.CompleteResponse.FromString,
                _registered_method=True)


class IRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClasses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCFG(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModules,
                    request_deserializer=ir_pb2.SourceRequest.FromString,
                    response_serializer=ir_pb2.ModuleResponse.SerializeToString,
            ),
            'GetClasses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClasses,
                    request_deserializer=ir_pb2.SourceRequest.FromString,
                    response_serializer=ir_pb2.ClassResponse.SerializeToString,
            ),
            'GetCFG': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCFG,
                    request_deserializer=ir_pb2.SourceRequest.FromString,
                    response_serializer=ir_pb2.CFGResponse.SerializeToString,
            ),
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=ir_pb2.SourceRequest.FromString,
                    response_serializer=ir_pb2.CompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ir.IRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ir.IRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ir.IRService/GetModules',
            ir_pb2.SourceRequest.SerializeToString,
            ir_pb2.ModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClasses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ir.IRService/GetClasses',
            ir_pb2.SourceRequest.SerializeToString,
            ir_pb2.ClassResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCFG(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ir.IRService/GetCFG',
            ir_pb2.SourceRequest.SerializeToString,
            ir_pb2.CFGResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ir.IRService/GetAll',
            ir_pb2.SourceRequest.SerializeToString,
            ir_pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
